/**
 * Country Codes Data
 * Complete list of country calling codes with flags
 */

export interface CountryCode {
  country: string;
  code: string;
  flag: string;
}

export const countryCodes: CountryCode[] = [
  { country: "Malaysia", code: "+60", flag: "🇲🇾" },
  { country: "Singapore", code: "+65", flag: "🇸🇬" },
  { country: "Indonesia", code: "+62", flag: "🇮🇩" },
  { country: "Afghanistan", code: "+93", flag: "🇦🇫" },
  { country: "Aland Islands", code: "+358", flag: "🇦🇽" },
  { country: "Albania", code: "+355", flag: "🇦🇱" },
  { country: "Algeria", code: "+213", flag: "🇩🇿" },
  { country: "AmericanSamoa", code: "+1684", flag: "🇦🇸" },
  { country: "Andorra", code: "+376", flag: "🇦🇩" },
  { country: "Angola", code: "+244", flag: "🇦🇴" },
  { country: "Anguilla", code: "+1264", flag: "🇦🇮" },
  { country: "Antarctica", code: "+672", flag: "🇦🇶" },
  { country: "Antigua and Barbuda", code: "+1268", flag: "🇦🇬" },
  { country: "Argentina", code: "+54", flag: "🇦🇷" },
  { country: "Armenia", code: "+374", flag: "🇦🇲" },
  { country: "Aruba", code: "+297", flag: "🇦🇼" },
  { country: "Australia", code: "+61", flag: "🇦🇺" },
  { country: "Austria", code: "+43", flag: "🇦🇹" },
  { country: "Azerbaijan", code: "+994", flag: "🇦🇿" },
  { country: "Bahamas", code: "+1242", flag: "🇧🇸" },
  { country: "Bahrain", code: "+973", flag: "🇧🇭" },
  { country: "Bangladesh", code: "+880", flag: "🇧🇩" },
  { country: "Barbados", code: "+1246", flag: "🇧🇧" },
  { country: "Belarus", code: "+375", flag: "🇧🇾" },
  { country: "Belgium", code: "+32", flag: "🇧🇪" },
  { country: "Belize", code: "+501", flag: "🇧🇿" },
  { country: "Benin", code: "+229", flag: "🇧🇯" },
  { country: "Bermuda", code: "+1441", flag: "🇧🇲" },
  { country: "Bhutan", code: "+975", flag: "🇧🇹" },
  { country: "Bolivia, Plurinational State of", code: "+591", flag: "🇧🇴" },
  { country: "Bosnia and Herzegovina", code: "+387", flag: "🇧🇦" },
  { country: "Botswana", code: "+267", flag: "🇧🇼" },
  { country: "Brazil", code: "+55", flag: "🇧🇷" },
  { country: "British Indian Ocean Territory", code: "+246", flag: "🇮🇴" },
  { country: "Brunei Darussalam", code: "+673", flag: "🇧🇳" },
  { country: "Bulgaria", code: "+359", flag: "🇧🇬" },
  { country: "Burkina Faso", code: "+226", flag: "🇧🇫" },
  { country: "Burundi", code: "+257", flag: "🇧🇮" },
  { country: "Cambodia", code: "+855", flag: "🇰🇭" },
  { country: "Cameroon", code: "+237", flag: "🇨🇲" },
  { country: "Canada", code: "+1", flag: "🇨🇦" },
  { country: "Cape Verde", code: "+238", flag: "🇨🇻" },
  { country: "Cayman Islands", code: "+345", flag: "🇰🇾" },
  { country: "Central African Republic", code: "+236", flag: "🇨🇫" },
  { country: "Chad", code: "+235", flag: "🇹🇩" },
  { country: "Chile", code: "+56", flag: "🇨🇱" },
  { country: "China", code: "+86", flag: "🇨🇳" },
  { country: "Christmas Island", code: "+61", flag: "🇨🇽" },
  { country: "Cocos (Keeling) Islands", code: "+61", flag: "🇨🇨" },
  { country: "Colombia", code: "+57", flag: "🇨🇴" },
  { country: "Comoros", code: "+269", flag: "🇰🇲" },
  { country: "Congo", code: "+242", flag: "🇨🇬" },
  { country: "Congo, The Democratic Republic of the Congo", code: "+243", flag: "🇨🇩" },
  { country: "Cook Islands", code: "+682", flag: "🇨🇰" },
  { country: "Costa Rica", code: "+506", flag: "🇨🇷" },
  { country: "Cote d'Ivoire", code: "+225", flag: "🇨🇮" },
  { country: "Croatia", code: "+385", flag: "🇭🇷" },
  { country: "Cuba", code: "+53", flag: "🇨🇺" },
  { country: "Cyprus", code: "+357", flag: "🇨🇾" },
  { country: "Czech Republic", code: "+420", flag: "🇨🇿" },
  { country: "Denmark", code: "+45", flag: "🇩🇰" },
  { country: "Djibouti", code: "+253", flag: "🇩🇯" },
  { country: "Dominica", code: "+1767", flag: "🇩🇲" },
  { country: "Dominican Republic", code: "+1849", flag: "🇩🇴" },
  { country: "Ecuador", code: "+593", flag: "🇪🇨" },
  { country: "Egypt", code: "+20", flag: "🇪🇬" },
  { country: "El Salvador", code: "+503", flag: "🇸🇻" },
  { country: "Equatorial Guinea", code: "+240", flag: "🇬🇶" },
  { country: "Eritrea", code: "+291", flag: "🇪🇷" },
  { country: "Estonia", code: "+372", flag: "🇪🇪" },
  { country: "Ethiopia", code: "+251", flag: "🇪🇹" },
  { country: "Falkland Islands (Malvinas)", code: "+500", flag: "🇫🇰" },
  { country: "Faroe Islands", code: "+298", flag: "🇫🇴" },
  { country: "Fiji", code: "+679", flag: "🇫🇯" },
  { country: "Finland", code: "+358", flag: "🇫🇮" },
  { country: "France", code: "+33", flag: "🇫🇷" },
  { country: "French Guiana", code: "+594", flag: "🇬🇫" },
  { country: "French Polynesia", code: "+689", flag: "🇵🇫" },
  { country: "Gabon", code: "+241", flag: "🇬🇦" },
  { country: "Gambia", code: "+220", flag: "🇬🇲" },
  { country: "Georgia", code: "+995", flag: "🇬🇪" },
  { country: "Germany", code: "+49", flag: "🇩🇪" },
  { country: "Ghana", code: "+233", flag: "🇬🇭" },
  { country: "Gibraltar", code: "+350", flag: "🇬🇮" },
  { country: "Greece", code: "+30", flag: "🇬🇷" },
  { country: "Greenland", code: "+299", flag: "🇬🇱" },
  { country: "Grenada", code: "+1473", flag: "🇬🇩" },
  { country: "Guadeloupe", code: "+590", flag: "🇬🇵" },
  { country: "Guam", code: "+1671", flag: "🇬🇺" },
  { country: "Guatemala", code: "+502", flag: "🇬🇹" },
  { country: "Guernsey", code: "+44", flag: "🇬🇬" },
  { country: "Guinea", code: "+224", flag: "🇬🇳" },
  { country: "Guinea-Bissau", code: "+245", flag: "🇬🇼" },
  { country: "Guyana", code: "+595", flag: "🇬🇾" },
  { country: "Haiti", code: "+509", flag: "🇭🇹" },
  { country: "Holy See (Vatican City State)", code: "+379", flag: "🇻🇦" },
  { country: "Honduras", code: "+504", flag: "🇭🇳" },
  { country: "Hong Kong", code: "+852", flag: "🇭🇰" },
  { country: "Hungary", code: "+36", flag: "🇭🇺" },
  { country: "Iceland", code: "+354", flag: "🇮🇸" },
  { country: "India", code: "+91", flag: "🇮🇳" },
  { country: "Iran, Islamic Republic of Persian Gulf", code: "+98", flag: "🇮🇷" },
  { country: "Iraq", code: "+964", flag: "🇮🇷" },
  { country: "Ireland", code: "+353", flag: "🇮🇪" },
  { country: "Isle of Man", code: "+44", flag: "🇮🇲" },
  { country: "Israel", code: "+972", flag: "🇮🇱" },
  { country: "Italy", code: "+39", flag: "🇮🇹" },
  { country: "Jamaica", code: "+1876", flag: "🇯🇲" },
  { country: "Japan", code: "+81", flag: "🇯🇵" },
  { country: "Jersey", code: "+44", flag: "🇯🇪" },
  { country: "Jordan", code: "+962", flag: "🇯🇴" },
  { country: "Kazakhstan", code: "+77", flag: "🇰🇿" },
  { country: "Kenya", code: "+254", flag: "🇰🇪" },
  { country: "Kiribati", code: "+686", flag: "🇰🇮" },
  { country: "Korea, Democratic People's Republic of Korea", code: "+850", flag: "🇰🇵" },
  { country: "Korea, Republic of South Korea", code: "+82", flag: "🇰🇷" },
  { country: "Kuwait", code: "+965", flag: "🇰🇼" },
  { country: "Kyrgyzstan", code: "+996", flag: "🇰🇬" },
  { country: "Laos", code: "+856", flag: "🇱🇦" },
  { country: "Latvia", code: "+371", flag: "🇱🇻" },
  { country: "Lebanon", code: "+961", flag: "🇱🇧" },
  { country: "Lesotho", code: "+266", flag: "🇱🇸" },
  { country: "Liberia", code: "+231", flag: "🇱🇷" },
  { country: "Libyan Arab Jamahiriya", code: "+218", flag: "🇱🇾" },
  { country: "Liechtenstein", code: "+423", flag: "🇱🇮" },
  { country: "Lithuania", code: "+370", flag: "🇱🇹" },
  { country: "Luxembourg", code: "+352", flag: "🇱🇺" },
  { country: "Macao", code: "+853", flag: "🇲🇴" },
  { country: "Macedonia", code: "+389", flag: "🇲🇰" },
  { country: "Madagascar", code: "+261", flag: "🇲🇬" },
  { country: "Malawi", code: "+265", flag: "🇲🇼" },
  { country: "Maldives", code: "+960", flag: "🇲🇻" },
  { country: "Mali", code: "+223", flag: "🇲🇱" },
  { country: "Malta", code: "+356", flag: "🇲🇹" },
  { country: "Marshall Islands", code: "+692", flag: "🇲🇭" },
  { country: "Martinique", code: "+596", flag: "🇲🇶" },
  { country: "Mauritania", code: "+222", flag: "🇲🇷" },
  { country: "Mauritius", code: "+230", flag: "🇲🇺" },
  { country: "Mayotte", code: "+262", flag: "🇾🇹" },
  { country: "Mexico", code: "+52", flag: "🇲🇽" },
  { country: "Micronesia, Federated States of Micronesia", code: "+691", flag: "🇫🇲" },
  { country: "Moldova", code: "+373", flag: "🇲🇩" },
  { country: "Monaco", code: "+377", flag: "🇲🇨" },
  { country: "Mongolia", code: "+976", flag: "🇲🇳" },
  { country: "Montenegro", code: "+382", flag: "🇲🇪" },
  { country: "Montserrat", code: "+1664", flag: "🇲🇸" },
  { country: "Morocco", code: "+212", flag: "🇲🇦" },
  { country: "Mozambique", code: "+258", flag: "🇲🇿" },
  { country: "Myanmar", code: "+95", flag: "🇲🇲" },
  { country: "Namibia", flag: "🇳🇦", code: "+264" },
  { country: "Nauru", code: "+674", flag: "🇳🇷" },
  { country: "Nepal", code: "+977", flag: "🇳🇵" },
  { country: "Netherlands", code: "+31", flag: "🇳🇱" },
  { country: "Netherlands Antilles", code: "+599", flag: "🇧🇶" },
  { country: "New Caledonia", code: "+687", flag: "🇳🇨" },
  { country: "New Zealand", code: "+64", flag: "🇳🇿" },
  { country: "Nicaragua", code: "+505", flag: "🇳🇮" },
  { country: "Niger", code: "+227", flag: "🇳🇪" },
  { country: "Nigeria", code: "+234", flag: "🇳🇬" },
  { country: "Niue", code: "+683", flag: "🇳🇺" },
  { country: "Norfolk Island", code: "+672", flag: "🇳🇫" },
  { country: "Northern Mariana Islands", code: "+1670", flag: "🇲🇵" },
  { country: "Norway", code: "+47", flag: "🇳🇴" },
  { country: "Oman", code: "+968", flag: "🇴🇲" },
  { country: "Pakistan", code: "+92", flag: "🇵🇰" },
  { country: "Palau", code: "+680", flag: "🇵🇼" },
  { country: "Palestinian Territory, Occupied", code: "+970", flag: "🇵🇸" },
  { country: "Panama", code: "+507", flag: "🇵🇦" },
  { country: "Papua New Guinea", code: "+675", flag: "🇵🇬" },
  { country: "Paraguay", code: "+595", flag: "🇵🇾" },
  { country: "Peru", code: "+51", flag: "🇵🇪" },
  { country: "Philippines", code: "+63", flag: "🇵🇭" },
  { country: "Pitcairn", code: "+872", flag: "🇵🇳" },
  { country: "Poland", code: "+48", flag: "🇵🇱" },
  { country: "Portugal", code: "+351", flag: "🇵🇹" },
  { country: "Puerto Rico", code: "+1939", flag: "🇵🇷" },
  { country: "Qatar", code: "+974", flag: "🇶🇦" },
  { country: "Romania", code: "+40", flag: "🇷🇴" },
  { country: "Russia", code: "+7", flag: "🇷🇺" },
  { country: "Rwanda", code: "+250", flag: "🇷🇼" },
  { country: "Reunion", code: "+262", flag: "🇷🇪" },
  { country: "Saint Barthelemy", code: "+590", flag: "🇧🇱" },
  { country: "Saint Helena, Ascension and Tristan Da Cunha", code: "+290", flag: "🇸🇭" },
  { country: "Saint Kitts and Nevis", code: "+1869", flag: "🇰🇳" },
  { country: "Saint Lucia", code: "+1758", flag: "🇱🇨" },
  { country: "Saint Martin", code: "+590", flag: "🇲🇫" },
  { country: "Saint Pierre and Miquelon", code: "+508", flag: "🇵🇲" },
  { country: "Saint Vincent and the Grenadines", code: "+1784", flag: "🇻🇨" },
  { country: "Samoa", code: "+685", flag: "🇼🇸" },
  { country: "San Marino", code: "+378", flag: "🇸🇲" },
  { country: "Sao Tome and Principe", code: "+239", flag: "🇸🇹" },
  { country: "Saudi Arabia", code: "+966", flag: "🇸🇦" },
  { country: "Senegal", code: "+221", flag: "🇸🇳" },
  { country: "Serbia", code: "+381", flag: "🇷🇸" },
  { country: "Seychelles", code: "+248", flag: "🇸🇨" },
  { country: "Sierra Leone", code: "+232", flag: "🇸🇱" },
  { country: "Slovakia", code: "+421", flag: "🇸🇰" },
  { country: "Slovenia", code: "+386", flag: "🇸🇮" },
  { country: "Solomon Islands", code: "+677", flag: "🇸🇧" },
  { country: "Somalia", code: "+252", flag: "🇸🇴" },
  { country: "South Africa", code: "+27", flag: "🇿🇦" },
  { country: "South Sudan", code: "+211", flag: "🇸🇸" },
  { country: "South Georgia and the South Sandwich Islands", code: "+500", flag: "🇬🇸" },
  { country: "Spain", code: "+34", flag: "🇪🇸" },
  { country: "Sri Lanka", code: "+94", flag: "🇱🇰" },
  { country: "Sudan", code: "+249", flag: "🇸🇩" },
  { country: "Suriname", code: "+597", flag: "🇸🇷" },
  { country: "Svalbard and Jan Mayen", code: "+47", flag: "🇸🇯" },
  { country: "Swaziland", code: "+268", flag: "🇸🇿" },
  { country: "Sweden", code: "+46", flag: "🇸🇪" },
  { country: "Switzerland", code: "+41", flag: "🇨🇭" },
  { country: "Syrian Arab Republic", code: "+963", flag: "🇸🇾" },
  { country: "Taiwan", code: "+886", flag: "🇹🇼" },
  { country: "Tajikistan", code: "+992", flag: "🇹🇯" },
  { country: "Tanzania, United Republic of Tanzania", code: "+255", flag: "🇹🇿" },
  { country: "Thailand", code: "+66", flag: "🇹🇭" },
  { country: "Timor-Leste", code: "+670", flag: "🇹🇱" },
  { country: "Togo", code: "+228", flag: "🇹🇬" },
  { country: "Tokelau", code: "+690", flag: "🇹🇰" },
  { country: "Tonga", code: "+676", flag: "🇹🇴" },
  { country: "Trinidad and Tobago", code: "+1868", flag: "🇹🇹" },
  { country: "Tunisia", code: "+216", flag: "🇹🇳" },
  { country: "Turkey", code: "+90", flag: "🇹🇷" },
  { country: "Turkmenistan", code: "+993", flag: "🇹🇲" },
  { country: "Turks and Caicos Islands", code: "+1649", flag: "🇹🇨" },
  { country: "Tuvalu", code: "+688", flag: "🇹🇻" },
  { country: "Uganda", code: "+256", flag: "🇺🇬" },
  { country: "Ukraine", code: "+380", flag: "🇺🇦" },
  { country: "United Arab Emirates", code: "+971", flag: "🇦🇪" },
  { country: "United Kingdom", code: "+44", flag: "🇬🇧" },
  { country: "United States", code: "+1", flag: "🇺🇸" },
  { country: "Uruguay", code: "+598", flag: "🇺🇾" },
  { country: "Uzbekistan", code: "+998", flag: "🇺🇿" },
  { country: "Vanuatu", code: "+678", flag: "🇻🇺" },
  { country: "Venezuela, Bolivarian Republic of Venezuela", code: "+58", flag: "🇻🇪" },
  { country: "Vietnam", code: "+84", flag: "🇻🇳" },
  { country: "Virgin Islands, British", code: "+1284", flag: "🇻🇬" },
  { country: "Virgin Islands, U.S.", code: "+1340", flag: "🇻🇮" },
  { country: "Wallis and Futuna", code: "+681", flag: "🇼🇫" },
  { country: "Yemen", code: "+967", flag: "🇾🇪" },
  { country: "Zambia", code: "+260", flag: "🇿🇲" },
  { country: "Zimbabwe", code: "+263", flag: "🇿🇼" }
];

export default countryCodes;
